version: '3.8'

services:
  web-hackathon:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - hackaton_hacknet


networks:
  hackaton_hacknet:
    external: true
